version: '3.8'

services:
  api:
    build: ./backend
    container_name: vmware-middleware
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - vmware-net
    restart: always

  web:
    build: ./frontend
    container_name: vmware-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - vmware-net
    restart: always

networks:
  vmware-net:
    driver: bridge
