version: '3.8'

services:
  api:
    build: ./backend
    container_name: vmware-middleware
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
    networks:
      - vmware-net
    restart: always

  web:
    build: ./frontend
    container_name: vmware-frontend
    ports:
      - "3008:3008"
    depends_on:
      - api
    networks:
      - vmware-net
    restart: always

networks:
  vmware-net:
    driver: bridge
